import NavigationBar from '@/components/layout/NavigationBar'
import './globals.css'
import { Inter } from 'next/font/google'
import { NotificationProvider } from '@/store/notification-context';
import Noti from './noti/page';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <NotificationProvider>
        <NavigationBar></NavigationBar>
          {children}
          <Noti />
        </NotificationProvider>
        
        </body>
    </html>
  )
}
